#!/bin/bash

echo "  *******************************  importing JediTasks table  *******************************"
echo " between $1 and $2 "

sqoop import \
    -D oraoop.disabled=true \
    -D mapred.child.java.opts="-Djava.security.egd=file:/dev/../dev/urandom" \
    --direct \
    --connect $JOB_ORACLE_CONNECTION_STRING \
    --table ATLAS_PANDA.JEDI_TASKS \
    --username $JOB_ORACLE_USER --password $JOB_ORACLE_PASS \
    --where "MODIFICATIONTIME between TO_DATE('$1','YYYY-MM-DD HH24:MI:SS') and TO_DATE('$2','YYYY-MM-DD HH24:MI:SS')" \
    --split-by JEDITASKID --as-avrodatafile --target-dir /atlas/analytics/tasks_temp \
    --columns JEDITASKID,TASKNAME,STATUS,USERNAME,REQID,OLDSTATUS,CLOUD,SITE,PRODSOURCELABEL,WORKINGGROUP,VO,CORECOUNT,TASKTYPE,PROCESSINGTYPE,TASKPRIORITY,CURRENTPRIORITY,ARCHITECTURE,TRANSUSES,TRANSHOME,TRANSPATH,LOCKEDBY,TERMCONDITION,SPLITRULE,WALLTIME,WALLTIMEUNIT,OUTDISKCOUNT,OUTDISKUNIT,WORKDISKCOUNT,WORKDISKUNIT,RAMCOUNT,RAMUNIT,IOINTENSITY,IOINTENSITYUNIT,WORKQUEUE_ID,PROGRESS,FAILURERATE,ERRORDIALOG,COUNTRYGROUP,PARENT_TID,EVENTSERVICE,TICKETID,TICKETSYSTEMTYPE,SUPERSTATUS,CAMPAIGN,MERGERAMCOUNT,MERGERAMUNIT,MERGEWALLTIME,MERGEWALLTIMEUNIT,NUMTHROTTLED,MERGECORECOUNT,GOAL,CPUTIME,CPUTIMEUNIT,CPUEFFICIENCY,BASEWALLTIME,AMIFLAG_OLD,AMIFLAG,NUCLEUS,BASERAMCOUNT,LOCKEDTIME,STATECHANGETIME,THROTTLEDTIME,ASSESSMENTTIME,CREATIONDATE,MODIFICATIONTIME,STARTTIME,ENDTIME,FROZENTIME,TTCREQUESTED,TTCPREDICTED,TTCPREDICTIONDATE,RESCUETIME,REQUESTTYPE,GSHARE,USEJUMBO,RESOURCE_TYPE,DISKIO,DISKIOUNIT \
    --map-column-java JEDITASKID=Long,TASKNAME=String,STATUS=String,USERNAME=String,REQID=Long,OLDSTATUS=String,CLOUD=String,SITE=String,PRODSOURCELABEL=String,WORKINGGROUP=String,VO=String,CORECOUNT=Long,TASKTYPE=String,PROCESSINGTYPE=String,TASKPRIORITY=Long,CURRENTPRIORITY=Long,ARCHITECTURE=String,TRANSUSES=String,TRANSHOME=String,TRANSPATH=String,LOCKEDBY=String,TERMCONDITION=String,SPLITRULE=String,WALLTIME=Long,WALLTIMEUNIT=String,OUTDISKCOUNT=Long,OUTDISKUNIT=String,WORKDISKCOUNT=Long,WORKDISKUNIT=String,RAMCOUNT=Long,RAMUNIT=String,IOINTENSITY=Long,IOINTENSITYUNIT=String,WORKQUEUE_ID=Integer,PROGRESS=Integer,FAILURERATE=Integer,ERRORDIALOG=String,COUNTRYGROUP=String,PARENT_TID=Long,EVENTSERVICE=Integer,TICKETID=String,TICKETSYSTEMTYPE=String,SUPERSTATUS=String,CAMPAIGN=String,MERGERAMCOUNT=Long,MERGERAMUNIT=String,MERGEWALLTIME=Long,MERGEWALLTIMEUNIT=String,NUMTHROTTLED=Integer,MERGECORECOUNT=Long,GOAL=Integer,CPUTIME=Long,CPUTIMEUNIT=String,CPUEFFICIENCY=Integer,BASEWALLTIME=Long,AMIFLAG_OLD=String,AMIFLAG=Integer,NUCLEUS=String,BASERAMCOUNT=Long,DISKIO=Long,DISKIOUNIT=String,REQUESTTYPE=String,GSHARE=String,RESOURCE_TYPE=String
rc=$?; if [[ $rc != 0 ]]; then 
    echo "problem with sqoop. Exiting."
    exit $rc
fi
echo "DONE"